version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: webauthn_db
    ports:
      - "3306:3306"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  # app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DB_HOST=db
  #     - DB_USER=root
  #     - DB_PASSWORD=my-secret-pw
  #     - DB_NAME=webauthn_db
  #     - SESSION_SECRET=secret123
  #   depends_on:
  #     - db